[package]
name = "d08"
version = "0.1.0"
edition = "2024"

[dependencies]
bimap = "0.6.3"
disjoint = "0.8.0"
fxhash = "0.2.1"
itertools = "0.14.0"
nom = "8.0.0"
rayon = "1.11.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
