[package]
name = "d10"
version = "0.1.0"
edition = "2024"

[dependencies]
good_lp = { version = "1.14.2", features = [
	"microlp",
], default-features = false }
itertools = "0.14.0"
nom = "8.0.0"
rayon = "1.11.0"
